### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by codediy** [0x8BitDev/MAPeD-SPReD#4]
https://github.com/0x8BitDev/MAPeD-SPReD/blob/master/src/SPReD/src/py_scripting/py_api.cs#L17
this may be fix 
![image](https://user-images.githubusercontent.com/20250924/141231227-48a77ae0-d075-4106-97bb-9d9c5bad2a30.png)

**Comment by 0x8BitDev** [comment]
Thanks! Fixed!
